[package]
name = "install_loader"
version = "0.1.0"
authors = ["Daniel Wong <drojfjord@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xz2 = "0.1"
tar = "0.4"
progress-streams = "*"
regex = "1"

# imgui dependencies
clipboard = "0.5"
glium = { version = "0.25", default-features = true }
image = "0.22"
imgui = { version = "0.3.0-pre", git = "https://github.com/Gekkio/imgui-rs" }
imgui-glium-renderer = { version = "0.3.0-pre", git = "https://github.com/Gekkio/imgui-rs"}
imgui-winit-support = { version = "0.3.0-pre", git = "https://github.com/Gekkio/imgui-rs" }

# Windows specific dependencies
winapi = "*"
user32-sys = "*"
kernel32-sys = "*"
