# PLEASE USE A LINTER (PYCHARM) TO EDIT THIS FILE - it will automatically detect syntax mistakes
language: python
matrix:
  include:
  # Use this linux machine to build the linux release and run Swift tests
  - name: Build Linux Installer and Run Swift Tests
    python: 3.8
    dist: xenial
    before_install:
    - sudo apt-get install -y aria2
    - sudo apt-get install -y p7zip-full
    - bash travis_install_swift.sh
    - pip3 install --upgrade pip
    env:
      - BUILD_MODE=NORMAL
      - RUN_TESTS=TRUE
  # Use this Windows machine to only build the 64-bit version of the installer
  - name: Build Windows 64-bit Installer
    os: windows
    language: shell
    before_install:
    - choco install aria2
    - choco install python3
    - choco install rust-ms --forcex86
    env:
    # ----------- UPDATE THIS LINE EACH TIME PYTHON VERSION CHANGES ----------------
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH
    # ------------------------------------------------------------------------------
      - BUILD_MODE=WINDOWS
# The below tasks are run across all machines, but gated using if statements on the environment variables
script:
- if [ "$BUILD_MODE" = "NORMAL" ]; then python travis_build_script.py && bash travis_validate_json.sh ; fi
- if [ "$BUILD_MODE" = "WINDOWS" ]; then python3 travis_build_script.py win || python travis_build_script.py win ; fi
deploy:
  provider: releases
  api_key:
    secure: K+IlUj3G2vwPhWCtGNOQc/T6pBXzQfH9lus5E8Qsr99IdS2wORsV006fThH6OfOTeRdHV9DWIbP84sN1qik0VNV7mVqjwkjEhaENr9HyBTmwzT0Stz0RKzHReWEo+J646Ssl4A5BksbL9MWHNsVsNs2dv2SaU4JxuM2J7BNp2QYCvqVGAVl2f+voQjIvAEumz6ZcXesq0qzGe/ojubXosNsoINQ57YcKwwszHexP80rNHqNdOmAjyzfGIf+VqRD7Ijr4svUiewzpOnWFR6+gUaiiGQbPzc9AkEIjHEv1D10zYngXKNW9A/WZ4vZy7xNVdLQyJBGLkH5ytK43otlBHLa1pzLXVOfc0+EyHfsapIrqsbQ4aM1sfMcXOIW5U9ZnLeyGH9fzApNQc6GjxVU1lCjcyZ4DioKL2potQ+Cu6tNF8WWVjL/R09dGsgQvqcS9x0umnHzdtVt46Qz5Js3KydlVH6ebTcAIadqMeFaJ4swvBTFE9EGVIV6YewItK6tF7dnpnebiymAqQY/gMNLWuXQ/M2ub6Nxd9uNe2KYo9CEZFnJ/71YFQEgnZPOwHJ+tyBh69KLo3gz4Q2vmkStDpVrfNTjW8FhLw/oq9/HDZlPy4iF3VWlLoICYNQ9x0wNFy0mXY2MMxGw2vm3TG3rSpAs+Vscgt4iPHYNsKkpj7j0=
  file_glob: true
  file: travis_installer_output/*
  skip_cleanup: true
  on:
    repo: 07th-mod/python-patcher
    tags: true
  draft: true

